### ISSUE TITLE
can't convert DmUser to Array

### ISSUE THREAD

**Issue by rujmah** [maxjustus/sinatra-authentication#20]
Hi - sorry can't figure this one out. 

I've associated the DmUser class with a customer class (i.e. Users have many Customers) like so:

``` ruby
class DmUser
  has n, :customers
end
class Customer
  include DataMapper::Resource

  property :id,  Serial
  property :name, String

  belongs_to :dm_user
end
```

When attempting to call the customers with the following in main.rb:

``` ruby
get '/dashboard'
  @customers = current_user.db_instance.customers
  haml :dash
end
```

and the following line in dash.haml:

``` ruby
- @customers.each {|c| puts c }
```

I get the error:

> TypeError at /dashboard
> can't convert DmUser to Array (DmUser#to_ary gives FalseClass)

Any ideas?

**Comment by rujmah** [comment]
As a workaround I've implemented the following:

``` ruby
@customers = Customer.all(:dm_user_id => current_user.id)
```

Does the job, but would be nice to know what I am doing wrong that the original code doesn't work.

**Comment by aleksclark** [comment]
Yea it seems that basically all has n, associations are broken (at least in datamapper). I tried the same thing, and encountered the same error. This is pretty major guys :/

**Comment by cmrd-senya** [comment]
The issue presents. This must be reopened.
