### ISSUE TITLE
RubyGems version shows 0.4.1 Github gemspec shows 0.4.2

### ISSUE THREAD

**Issue by caleywoods** [maxjustus/sinatra-authentication#22]
I'm experiencing the issue from #15 where you get the cannot convert pathname to string. I think the .4.2 version might fix this? All you get when you gem install sinatra-authentication is .4.1 from rubygems.

**Comment by cmhobbs** [comment]
A new gem does need to be pushed.  I'll try to roll out some fixes this week.

**Comment by caleywoods** [comment]
Thanks, I'd submit you some code but can't really do that with this issue..

**Comment by cmhobbs** [comment]
I haven't forgotten you, I just got caught up with family issues.  I forked the project and intend to get to work on this issue this week or weekend.

**Comment by timmillwood** [comment]
https://github.com/maxjustus/sinatra-authentication/pull/39

**Comment by cmhobbs** [comment]
Thanks for the fix.
