### ISSUE TITLE
Broken Dependency: rack-flash incompatible with Rack > 1.3.6

### ISSUE THREAD

**Issue by thehack** [maxjustus/sinatra-authentication#30]
Just and FYI. This has been submitted to rack-flash, but remains an open issue. 'sinatra-flash' seems to work. Maybe include that instead?

**Comment by EHadoux** [comment]
I think your problem solved with the commit about rack-flash -> rack-flash3.

**Comment by cmhobbs** [comment]
I'll look into this hopefully sometime this week.
