### ISSUE TITLE
Issues with Mongoid 3?

### ISSUE THREAD

**Issue by slackjaw** [maxjustus/sinatra-authentication#37]
Hi there,

Been trying to use sinatra-authentication in a very simple test app with mongoid3 and have been running into some odd problems.  Probably operator error, but worth mentioning, I thought.  

When using mongoid 3, I often get errors like:
ArgumentError at /login
wrong number of arguments (1 for 0)

an easy way to get this is to enter bad credentials into the login screen.  Another way to get it is to try to access current_user after a successful login.  The same behavior is seen in 3.0.0-3.0.3 but the problems all go away when I switch to mongoid 2.4.12.  I am using Ruby 1.9.3

Here is a paste: http://pastebin.com/TzEaWKPa

It looks like one of the problems is in line 14 of mongoid_adapter.rb, which is:
MongoidUser.first(:conditions => hash)

It looks as though the proper usage in Mongoid 3 is
MongoidUser.find(:conditions => hash).first

**Comment by slackjaw** [comment]
Just noticed that a fix had been submitted a few weeks ago in 0.4.2.  I manually updated to that version and all is well.

**Comment by aaronbieber** [comment]
I am experiencing this particular bug, but I don't see an 0.4.2 tag in this project. Am I missing something?

**Comment by cmhobbs** [comment]
The latest tag is 0.4.1 and it should've been resolved.  What version of the gem are you using?

**Comment by pbaille** [comment]
hello,
i've got the same issue with 0.4.1 and mongoid 3.0.23
am i missing something?
thanks

**Comment by mikefowler** [comment]
For those experiencing this issue, the "solution" is to source the gem directly from this repository. The latest version of the gem on RubyGems is outdated and doesn't include the fix mentioned by @nilmethod above.

@maxjustus and/or @nilmethod, any chance that change could be pushed to RubyGems?

_Edit_

Reference for those who need it:

```
gem 'sinatra-authentication', git: 'git@github.com:maxjustus/sinatra-authentication.git'
```

**Comment by cmhobbs** [comment]
I don't have the credentials to push the gem.  @maxjustus will have to handle that.
