### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by apotheon** [maxjustus/sinatra-authentication#38]
What are the license terms for sinatra-authentication?  Please add a license file, perhaps for the [Simplified BSD License](https://github.com/ruby/ruby/blob/trunk/BSDL) used by Ruby itself.

**Comment by cmhobbs** [comment]
@maxjustus thoughts? I can't make a call on this one, it's your baby.

**Comment by apotheon** [comment]
bump

It has been a while since I posted this.  Is the project maintainer MIA?

**Comment by cmhobbs** [comment]
We're not MIA, we're just very busy outside of the project and it's not my baby so I can't make a call on licensing.  I'll ping @maxjustus directly.

**Comment by cmhobbs** [comment]
Unlicense selected for this project.  See `UNLICENSE` in the repo and unlicense.org for further details.

**Comment by apotheon** [comment]
Thank you for resolving this issue.  I appreciate it.

**Comment by cmhobbs** [comment]
No worries.  I hope to knock out some of the other issues piling up this weekend.
