### ISSUE TITLE
current_user not being created

### ISSUE THREAD

**Issue by mhuebert** [maxjustus/sinatra-authentication#4]
I'm using the latest versions of DM, Sinatra and sinatra-authentication and I am perplexed by a recurrent problem with the current_user object not being created. This causes a server error when I have -if current_user.admin? in my templates (no method 'admin' for nil:nilClass).

When it occurs, the only predictable thing I can do to get my site back running is remove all references to current_user from my templates. The /login and /logout pages still work. The problem seems to go away and come back at will; I haven't yet detected the pattern.  

Can anyone think of what might prevent current_user from being created? I am a novice at this so I may be missing something obvious.

Thankyou muchly.

**Comment by maxjustus** [comment]
Strange.. The only times I get that error are when I'm switching database backends and the browser session is referencing a user id that doesn't exist.. Manually going to /logout and logging back in fixes it for me. Seems to me your issue might be a bit different though. Are you possibly using the auto_migrate! method somewhere in your code? That'll wipe out your database whenever it's run.

**Comment by mhuebert** [comment]
Hmm, interesting. Next time it happens I will try this. I am using auto_upgrade! but have been periodically using using auto_migrate! in the process of troubleshooting. It's possible that while troubleshooting other problems I'm causing this one. I'll spend another day coding and see what happens. Thanks for the pointer!

**Comment by mhuebert** [comment]
Another thought, would it make sense for current_user to default to guest in situations like this?

**Comment by mhuebert** [comment]
This happened again, and manually logging out worked to solve it.... thanks again.

**Comment by maxjustus** [comment]
No problem! I suppose current_user ought to default to a guest instance.. I'll look into it.
