### ISSUE TITLE
Setting sinatra_authentication_view_path not working

### ISSUE THREAD

**Issue by brianfryer** [maxjustus/sinatra-authentication#42]
The method to override default views as described here (https://github.com/maxjustus/sinatra-authentication#overriding-default-views) does not seem to be working correctly.

I have the following directory structure...

```
/app
  /views
    edit.haml
    index.haml
    layout.haml
    login.haml
    show.haml
    signup.haml
  app.rb
```

...with this line of code in my app.rb file...

```
set :sinatra_authentication_view_path, Pathname(__FILE__).dirname + "views/"
```

...and the haml templates in `/views` are not being used.

**Comment by timmillwood** [comment]
Try

```
configure do
  set :sinatra_authentication_view_path, Pathname(__FILE__).dirname.expand_path + "views/"
end
```

**Comment by rupe** [comment]
I see that you are also setting the view path to the same one that sinatra-authentication uses internally for its layout files anyway ("views"). Will that work?

**Comment by timmillwood** [comment]
Works fine for me, see https://github.com/timmillwood/millwoodonline/blob/master/web.rb

**Comment by rupe** [comment]
Good to know, thanks.
