### ISSUE TITLE
Flash message marked as 'notice', when it should be 'error'.

### ISSUE THREAD

**Issue by rupe** [maxjustus/sinatra-authentication#46]
I'm not sure why this is happening, as it seems to be correct in the current code here, but the login error "The email or password you entered is incorrect." is being marked as ':notice', instead of ':error' in RackFlash. The content of the Rack::FLash object follows:

'#FlashHash @values={:notice=>"The email or password you entered is incorrect."} @cache={}'

**Comment by cmhobbs** [comment]
I can't seem to duplicate this issue.  What version of the gem are you using?

**Comment by rupe** [comment]
Sorry, I don't recall, since posting I have fixed it and a few other issues (like changing to 'settings' , rack-flash3, and prepending "sa_" to view filenames, which helps) on my own fork. I didn't make a pull request as I've also removed parts of the original code that I would never need, but others may use (rufus tokyo etc).
