### ISSUE TITLE
Use rack-flash3 instead of rack-flash

### ISSUE THREAD

**Issue by rupe** [maxjustus/sinatra-authentication#47]
There are problems with the latest release of Rack and rack-flash. Rack-Flash3 addresses these issues, but sinatra-authentication does not recognize it as a replacement for rack-flash.

**Comment by cmhobbs** [comment]
Could you provide some more details or any specific errors you're getting?  Thanks.

**Comment by gojohnnygo** [comment]
@nilmethod This link sums up the issue.  https://github.com/nakajima/rack-flash/issues/8

The Sinatra FAQ is now linking to a forked version of rack-flash.  http://www.sinatrarb.com/faq#flash

**Comment by cmhobbs** [comment]
Thanks for the input.  I'll see what I can do.

**Comment by pocketcalamity** [comment]
having this issue as well. would love to see a fix! :)

**Comment by cmhobbs** [comment]
Still on my list, sorry guys.  I've been swamped lately.  I'll see if I can't take a look at this on Thursday, I've got an opening then.

**Comment by rupe** [comment]
It should just be a matter of Pulling one of the many forks that have already implemented it. I've done it, plus fixed the settings/options deprecation issue, plus added a missing Flash message, added a "signup_closed" setting, and am in the middle of adding an Invite system for the signup module. I would have requested a pull, but this is my first time modifying another's work, so wanted to make sure everything was perfect before doing so ...

**Comment by EHadoux** [comment]
I may be mistaken but this commit (841cc6006e0fe7eb197561c6b0278bfaf5db35c2) doesn't already fix that?

**Comment by cmhobbs** [comment]
I believe the stated commit resolves the issue.
