### ISSUE TITLE
What license is sinatra-authentication?

### ISSUE THREAD

**Issue by kiafaldorius** [maxjustus/sinatra-authentication#5]
May I ask what license sinatra-authentication is released as? I'm considering extending or adding to this project when I have time, but without a license file I'm not sure. (Sorry to be so asinine like that, I just like to stay safe.)

I would assume this project is MIT like most ruby projects?

**Comment by maxjustus** [comment]
yeah, it's MIT license

**Comment by kiafaldorius** [comment]
Thanks!

**Comment by maxjustus** [comment]
No problem! :)
