### ISSUE TITLE
Validation with mongo mapper

### ISSUE THREAD

**Issue by cearls** [maxjustus/sinatra-authentication#6]
I'm using mongo mapper. I'm able to create users, but it's not returning errors when you don't use a unique email or don't enter passwords on signup.

**Comment by maxjustus** [comment]
are you using the gem version? The version in the repo fixes this issue. I'll be doing a release soon.

**Comment by cearls** [comment]
yes, the gem version. thanks.

**Comment by cearls** [comment]
close
