### ISSUE TITLE
User class confusion

### ISSUE THREAD

**Issue by jphastings** [maxjustus/sinatra-authentication#7]
I'm using sinatra-authentication with Mongo Mapper, but the `method_missing` way of accessing the underlying Mongo class isn't quite enough for accessing some of MM's features eg:

```
class MmUser
  many :addresses
end

class Address
  key :street, String
end

# This works
p current_user.addresses

# This doesn't
current_user.addresses << Address.new(:street => 'mine')
current_user.save
```

Is there a way to access the underlying class? Could the `User` class be configured to use delegate rather than method_missing?
@huboard:{"order":10.5}

**Comment by maxjustus** [comment]
I'll look into using delegation, but for now I've added a db_instance method to current user. Using db_instance is perhaps safer, since it eradicates the possibility of their being naming conflicts between sinatra auth's User adapter and the underlying ORM. Thoughts?
