### ISSUE TITLE
Using the database outside of sinatra-authenticate

### ISSUE THREAD

**Issue by jphastings** [maxjustus/sinatra-authentication#8]
If I want to build a cron job that works on the same database as your `sinatra-authentication` has auto-manufactured I can't just `require 'sinatra-authentication'` and let it take care of everything for me because that requires sinatra.

It would be nice if I could have, say, only the following lines:

```
require 'mongo_mapper'
require 'sinatra-authentication/models'
```

in a non-sinatra script (eg. environment.rb), and have the `MmUser` class prepped with all the same keys as it would in my sinatra app.

---

Hehe, I got a little carried away testing out how this could be done and made something that works! See what you think: jphastings/sinatra-authentication@ee842513caee90ee39c8566f71e305f02328264f

**Comment by maxjustus** [comment]
Merged yr change! Thanks!
